-- This file is Free Software under the Apache-2.0 License
-- without warranty, see README.md and LICENSES/Apache-2.0.txt for details.
--
-- SPDX-License-Identifier: Apache-2.0
--
-- SPDX-FileCopyrightText: 2026 SecurityPortal contributors

-- Base schema for the SecurityPortal advisory store.
--
-- This mirrors the proven ISDuBA data model (advisories parent + documents
-- child with generated columns extracted from the CSAF JSONB, plus a
-- trigger-maintained "latest" pointer) but drops everything tied to ISDuBA's
-- authenticated workflow (comments, events, sources, stored queries, ssvc).
--
-- Deferred to later migrations (kept out here on purpose):
--   * tsvector / full-text search columns + GIN index (FTS migration).
--   * unique_cves / documents_cves CVE extraction tables + trigger.
--   * documents_products vendor/product extraction table + trigger.

-- Bookkeeping table for the migration runner. Recreating the schema from
-- scratch is driven by the presence/absence of this table.
CREATE TABLE versions (
    version     int PRIMARY KEY,
    description text NOT NULL,
    time        timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Tracking status as defined by the CSAF specification.
CREATE TYPE status AS ENUM (
    'draft', 'final', 'interim');

-- Helper functions extracting facet values from the CSAF JSONB. These are
-- IMMUTABLE so they can back STORED generated columns.

CREATE FUNCTION utc_timestamp(text) RETURNS timestamp with time zone AS $$
    SELECT $1::timestamp with time zone AT time zone 'utc'
$$ LANGUAGE SQL IMMUTABLE;

CREATE FUNCTION text_to_status(text) RETURNS public.status AS $$
    SELECT $1::public.status
$$ LANGUAGE SQL IMMUTABLE;

CREATE FUNCTION revision_history_length(jsonb) RETURNS int AS $$
    SELECT jsonb_array_length(jsonb_path_query($1, '$.document.tracking.revision_history'))
$$ LANGUAGE SQL IMMUTABLE;

CREATE FUNCTION max_cvss2_score(jsonb) RETURNS float AS $$
    SELECT max(a::float) FROM
        jsonb_path_query(
            $1, '$.vulnerabilities[*].scores[*].cvss_v2.baseScore') a
$$ LANGUAGE SQL IMMUTABLE;

CREATE FUNCTION max_cvss3_score(jsonb) RETURNS float AS $$
    SELECT max(a::float) FROM
        jsonb_path_query(
            $1, '$.vulnerabilities[*].scores[*].cvss_v3.baseScore') a
$$ LANGUAGE SQL IMMUTABLE;

-- advisories is the parent keyed by (tracking_id, publisher). Each advisory
-- collects one or more document revisions; latest_document_id denormalises the
-- current head for cheap lookups (documents.latest is the source of truth).
-- withdrawn marks an advisory that is no longer present in the provider feeds
-- (deletion = tombstone, OQ-3). The API/UI will later treat withdrawn
-- advisories specially: their permalinks stay resolvable but render a "no longer
-- published" notice instead of the advisory body, rather than returning a 404.
-- Documents are retained (no hard delete) so data and permalinks survive a
-- provider that temporarily drops and later re-publishes an advisory.
CREATE TABLE advisories (
    id                 int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tracking_id        text NOT NULL,
    publisher          text NOT NULL,
    latest_document_id int,
    recent             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    withdrawn          boolean NOT NULL DEFAULT false,
    withdrawn_at       timestamptz,
    UNIQUE(tracking_id, publisher)
);

CREATE INDEX advisories_recent_idx ON advisories(recent);
CREATE INDEX advisories_withdrawn_idx ON advisories(withdrawn) WHERE withdrawn;

-- ingest_state keys an incremental-poll watermark per feed URL. watermark is the
-- newest advisory timestamp accepted during the last fully successful poll;
-- advanced only after a complete cycle so an interrupted poll stays resumable.
CREATE TABLE ingest_state (
    feed_url    text PRIMARY KEY,
    watermark   timestamptz NOT NULL,
    updated     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- documents holds one row per advisory revision. The facet columns are
-- GENERATED from the CSAF JSONB so they cannot drift from the stored document.
CREATE TABLE documents (
    id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    advisories_id   int NOT NULL
                    REFERENCES advisories(id) ON DELETE CASCADE,
    latest          boolean,
    version         text NOT NULL
                    GENERATED ALWAYS AS (document #>> '{document,tracking,version}') STORED,
    rev_history_length int
                    GENERATED ALWAYS AS (revision_history_length(document)) STORED,
    tracking_status status
                    GENERATED ALWAYS AS (
                        text_to_status(document #>> '{document,tracking,status}')) STORED,
    current_release_date timestamptz
                    GENERATED ALWAYS AS (
                        utc_timestamp(document #>> '{document,tracking,current_release_date}')) STORED,
    initial_release_date timestamptz
                    GENERATED ALWAYS AS (
                        utc_timestamp(document #>> '{document,tracking,initial_release_date}')) STORED,
    tlp             text
                    GENERATED ALWAYS AS (document #>> '{document,distribution,tlp,label}') STORED,
    title           text
                    GENERATED ALWAYS AS (document #>> '{document,title}') STORED,
    category        text
                    GENERATED ALWAYS AS (document #>> '{document,category}') STORED,
    publisher_name  text
                    GENERATED ALWAYS AS (document #>> '{document,publisher,name}') STORED,
    cvss_v2_score   float
                    GENERATED ALWAYS AS (max_cvss2_score(document)) STORED,
    cvss_v3_score   float
                    GENERATED ALWAYS AS (max_cvss3_score(document)) STORED,
    critical        float
                    GENERATED ALWAYS AS (
                        coalesce(max_cvss3_score(document), max_cvss2_score(document))) STORED,
    lang            text
                    GENERATED ALWAYS AS (document #>> '{document,lang}') STORED,
    document        jsonb COMPRESSION lz4 NOT NULL,
    original        bytea COMPRESSION lz4,
    signature       bytea,

    UNIQUE (advisories_id, version, rev_history_length, tracking_status)
);

-- At most one revision per advisory may be flagged as the latest head.
CREATE UNIQUE INDEX only_one_latest_constraint
    ON documents (advisories_id)
    WHERE latest;

-- update_advisory promotes a freshly inserted document to "latest" when it is
-- newer than the current head (by release date, then revision history length)
-- and keeps advisories.latest_document_id / recent in sync.
CREATE FUNCTION update_advisory() RETURNS trigger AS $$
    DECLARE
        old_id           int;
        old_rev_length   int;
        old_release_date timestamptz;
    BEGIN
        SELECT id, rev_history_length, current_release_date
            INTO old_id, old_rev_length, old_release_date
            FROM documents
            WHERE latest AND advisories_id = NEW.advisories_id;

        IF NOT FOUND THEN -- No latest yet -> the new document leads.
            UPDATE documents SET latest = TRUE WHERE id = NEW.id;
            UPDATE advisories
                SET latest_document_id = NEW.id,
                    recent = CURRENT_TIMESTAMP
                WHERE id = NEW.advisories_id;
        ELSE
            -- Check whether the new record is in fact newer than the old one.
            IF NEW.current_release_date > old_release_date OR
               (NEW.current_release_date = old_release_date AND
                NEW.rev_history_length > old_rev_length)
            THEN
                -- Take over lead.
                UPDATE documents SET latest = FALSE WHERE id = old_id;
                UPDATE documents SET latest = TRUE  WHERE id = NEW.id;
                UPDATE advisories
                    SET latest_document_id = NEW.id,
                        recent = CURRENT_TIMESTAMP
                    WHERE id = NEW.advisories_id;
            ELSE
                -- Older revision arrived late; just bump the recent marker.
                UPDATE advisories
                    SET recent = CURRENT_TIMESTAMP
                    WHERE id = NEW.advisories_id;
            END IF;
        END IF;
        RETURN NULL;
    END;
$$ LANGUAGE plpgsql;

-- delete_advisory re-establishes a new head after the latest document was
-- deleted, or removes the orphaned advisory when no revisions remain.
CREATE FUNCTION delete_advisory() RETURNS trigger AS $$
    DECLARE
        lead_id int;
    BEGIN
        -- Update is only needed if the deleted one was the latest.
        IF OLD.latest THEN
            SELECT id
                INTO lead_id
                FROM documents
                WHERE advisories_id = OLD.advisories_id
                ORDER BY current_release_date DESC, rev_history_length DESC;
            IF FOUND THEN
                UPDATE documents SET latest = TRUE WHERE id = lead_id;
                UPDATE advisories
                    SET latest_document_id = lead_id
                    WHERE id = OLD.advisories_id;
            ELSE -- No documents left for advisory -> delete the advisory.
                DELETE FROM advisories WHERE id = OLD.advisories_id;
            END IF;
        END IF;
        RETURN NULL;
    END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER insert_document
    AFTER INSERT
    ON documents
    FOR EACH ROW EXECUTE FUNCTION update_advisory();

CREATE TRIGGER delete_document
    AFTER DELETE
    ON documents
    FOR EACH ROW EXECUTE FUNCTION delete_advisory();

-- Facet indexes: btree over the columns the read API filters / sorts on.
CREATE INDEX documents_current_release_date_idx ON documents (current_release_date);
CREATE INDEX documents_initial_release_date_idx ON documents (initial_release_date);
CREATE INDEX documents_tlp_idx ON documents (tlp);
CREATE INDEX documents_category_idx ON documents (category);
CREATE INDEX documents_publisher_name_idx ON documents (publisher_name);
CREATE INDEX documents_lang_idx ON documents (lang);
CREATE INDEX documents_critical_idx ON documents (coalesce(critical, '0'::double precision) DESC);
