-- This file is Free Software under the Apache-2.0 License
-- without warranty, see README.md and LICENSES/Apache-2.0.txt for details.
--
-- SPDX-License-Identifier: Apache-2.0
--
-- SPDX-FileCopyrightText: 2026 Tommy Lehmann

-- Facet extraction tables + language-aware full-text search (plan tasks 15+16,
-- ADR-0005).
--
-- As with 001, these objects are also baked into the consolidated 000-setup.sql,
-- so a freshly initialised database already has them and never runs this script
-- (the runner records 000 as the latest version on a fresh install). This
-- incremental exists for databases created from an EARLIER 000-setup that
-- predates facet extraction / FTS; it is written idempotently (IF NOT EXISTS,
-- CREATE OR REPLACE, DROP TRIGGER IF EXISTS) so both a fresh DB and an
-- already-migrated demo DB converge to the identical schema.
--
--   1. unique_cves / documents_cves + extract_cves trigger (ported from ISDuBA
--      023-document_cve.sql): every /vulnerabilities[]/cve drives the CVE facet
--      and free-text CVE matching.
--   2. documents_products + extract_products trigger: vendor/product names walked
--      out of product_tree (branches recursively + full_product_names) for the
--      product/vendor facet.
--   3. documents.tsv tsvector + extract_tsv trigger + GIN index: language-aware
--      weighted full-text search. The config is chosen at row time from lang, so
--      it cannot be a generated column (the choice is not IMMUTABLE).
--   4. A one-shot idempotent backfill of all three for pre-existing rows.

-- ---------------------------------------------------------------------------
-- 1. CVE extraction (port of ISDuBA 023-document_cve.sql; single-user model so
--    no GRANT templating).
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS unique_cves (
    id  int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cve text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS documents_cves (
    documents_id int NOT NULL REFERENCES documents(id)   ON DELETE CASCADE,
    cve_id       int NOT NULL REFERENCES unique_cves(id) ON DELETE CASCADE,
    UNIQUE(documents_id, cve_id)
);

CREATE INDEX IF NOT EXISTS documents_cves_cve_id_idx ON documents_cves (cve_id);

-- extract_cves rebuilds the CVE links for one document. unique_cves is a shared
-- dictionary (ON CONFLICT DO NOTHING), documents_cves the per-document join.
CREATE OR REPLACE FUNCTION extract_cves() RETURNS TRIGGER AS $$
    BEGIN
        DELETE FROM documents_cves WHERE documents_id = NEW.id;
        WITH cves_from_document AS (
            SELECT
                id AS doc_id,
                jsonb_array_elements_text(
                    jsonb_path_query_array(document, '$.vulnerabilities."cve"')) AS cve
            FROM documents
            WHERE id = NEW.id
        ),
        inserted AS (
            INSERT INTO unique_cves (cve)
            SELECT cve FROM cves_from_document
            ON     CONFLICT DO NOTHING
            RETURNING id, cve
        ),
        selected AS (
            SELECT id, unique_cves.cve AS cve
            FROM unique_cves
            JOIN cves_from_document ON unique_cves.cve = cves_from_document.cve
        ),
        resolved AS (
            SELECT * FROM selected
            UNION
            SELECT * FROM inserted
        )
        INSERT INTO documents_cves (documents_id, cve_id)
        SELECT DISTINCT doc_id, resolved.id
        FROM cves_from_document JOIN resolved ON cves_from_document.cve = resolved.cve;
        RETURN NULL;
    END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS extract_cves_trigger_insert ON documents;
CREATE TRIGGER extract_cves_trigger_insert AFTER INSERT
    ON documents
    FOR EACH ROW
    EXECUTE FUNCTION extract_cves();

DROP TRIGGER IF EXISTS extract_cves_trigger_update ON documents;
CREATE TRIGGER extract_cves_trigger_update AFTER UPDATE
    ON documents
    FOR EACH ROW
    WHEN (NEW.document <> OLD.document)
    EXECUTE FUNCTION extract_cves();

-- ---------------------------------------------------------------------------
-- 2. Product / vendor extraction (NEW vs ISDuBA, ADR-0004/0005).
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS documents_products (
    documents_id int NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    vendor       text,
    product      text,
    UNIQUE(documents_id, vendor, product)
);

CREATE INDEX IF NOT EXISTS documents_products_vendor_idx  ON documents_products (vendor);
CREATE INDEX IF NOT EXISTS documents_products_product_idx ON documents_products (product);

-- document_product_pairs returns the (vendor, product) pairs for one CSAF
-- document. It is a stable, set-returning helper reused by both the trigger and
-- the backfill so the extraction rules live in one place.
--
-- The product_tree is walked two ways:
--
--   * branches[*] recursively. A recursive CTE descends the nesting, threading
--     down the nearest ancestor "vendor" branch name. At each node whose
--     category is product_name or product_family we emit (ancestor vendor, this
--     name); a "vendor" node also emits (vendor, NULL) so a vendor with no
--     enumerated products is still a filterable facet value.
--   * full_product_names[*].name — these are flat, denormalised product strings
--     with no vendor context, emitted as (NULL, name).
--
-- Empty strings are normalised to NULL and all-NULL rows are dropped.
CREATE OR REPLACE FUNCTION document_product_pairs(doc jsonb)
    RETURNS TABLE (vendor text, product text) AS $$
    WITH RECURSIVE tree AS (
        -- Root branches: no inherited vendor yet.
        SELECT
            branch,
            CASE WHEN branch->>'category' = 'vendor'
                 THEN branch->>'name' END AS vendor
        FROM jsonb_array_elements(
                 COALESCE(doc #> '{product_tree,branches}', '[]'::jsonb)) AS branch
        UNION ALL
        -- Descend, carrying the nearest ancestor vendor downward.
        SELECT
            child,
            CASE WHEN child->>'category' = 'vendor'
                 THEN child->>'name'
                 ELSE tree.vendor END
        FROM tree,
             LATERAL jsonb_array_elements(
                 COALESCE(tree.branch->'branches', '[]'::jsonb)) AS child
    ),
    from_branches AS (
        -- Product/family leaves: (ancestor vendor, this name).
        SELECT vendor, branch->>'name' AS product
        FROM tree
        WHERE branch->>'category' IN ('product_name', 'product_family')
        UNION
        -- Vendor nodes themselves, so a bare vendor is still facetable.
        SELECT branch->>'name' AS vendor, NULL::text AS product
        FROM tree
        WHERE branch->>'category' = 'vendor'
    ),
    from_full_names AS (
        SELECT NULL::text AS vendor, fpn->>'name' AS product
        FROM jsonb_array_elements(
                 COALESCE(doc #> '{product_tree,full_product_names}', '[]'::jsonb)) AS fpn
    ),
    combined AS (
        SELECT vendor, product FROM from_branches
        UNION
        SELECT vendor, product FROM from_full_names
    )
    SELECT
        NULLIF(btrim(vendor),  '') AS vendor,
        NULLIF(btrim(product), '') AS product
    FROM combined
    WHERE NULLIF(btrim(vendor), '') IS NOT NULL
       OR NULLIF(btrim(product), '') IS NOT NULL;
$$ LANGUAGE SQL STABLE;

-- extract_products rebuilds the product/vendor rows for one document.
CREATE OR REPLACE FUNCTION extract_products() RETURNS TRIGGER AS $$
    BEGIN
        DELETE FROM documents_products WHERE documents_id = NEW.id;
        INSERT INTO documents_products (documents_id, vendor, product)
        SELECT DISTINCT NEW.id, p.vendor, p.product
        FROM document_product_pairs(NEW.document) AS p
        ON CONFLICT DO NOTHING;
        RETURN NULL;
    END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS extract_products_trigger_insert ON documents;
CREATE TRIGGER extract_products_trigger_insert AFTER INSERT
    ON documents
    FOR EACH ROW
    EXECUTE FUNCTION extract_products();

DROP TRIGGER IF EXISTS extract_products_trigger_update ON documents;
CREATE TRIGGER extract_products_trigger_update AFTER UPDATE
    ON documents
    FOR EACH ROW
    WHEN (NEW.document <> OLD.document)
    EXECUTE FUNCTION extract_products();

-- ---------------------------------------------------------------------------
-- 3. Full-text search — language-aware, trigger-maintained tsvector (OQ-2:
--    tsvector only, no pg_trgm).
-- ---------------------------------------------------------------------------

ALTER TABLE documents ADD COLUMN IF NOT EXISTS tsv tsvector;

-- fts_config maps a CSAF lang tag to a Postgres text-search config. German for
-- de*, English for en*, otherwise simple (which still tokenises but does no
-- language-specific stemming/stop-wording) so non-DE/EN documents stay
-- searchable.
CREATE OR REPLACE FUNCTION fts_config(lang text) RETURNS regconfig AS $$
    SELECT CASE
        WHEN lower(coalesce(lang, '')) LIKE 'de%' THEN 'german'::regconfig
        WHEN lower(coalesce(lang, '')) LIKE 'en%' THEN 'english'::regconfig
        ELSE 'simple'::regconfig
    END;
$$ LANGUAGE SQL IMMUTABLE;

-- document_tsv builds the weighted search vector for one document under the
-- given config. Weighting (A highest): title + CVEs are A; product/vendor names
-- and publisher are B; notes text is C. CVEs are pulled straight from the JSONB
-- (the documents_cves rows are not guaranteed populated yet during the same
-- statement, and reading the JSONB keeps this function self-contained).
CREATE OR REPLACE FUNCTION document_tsv(doc jsonb, cfg regconfig) RETURNS tsvector AS $$
    WITH
    title AS (
        SELECT coalesce(doc #>> '{document,title}', '') AS txt
    ),
    cves AS (
        SELECT string_agg(c, ' ') AS txt
        FROM jsonb_array_elements_text(
                 jsonb_path_query_array(doc, '$.vulnerabilities."cve"')) AS c
    ),
    products AS (
        SELECT string_agg(
            concat_ws(' ', p.vendor, p.product), ' ') AS txt
        FROM document_product_pairs(doc) AS p
    ),
    publisher AS (
        SELECT coalesce(doc #>> '{document,publisher,name}', '') AS txt
    ),
    notes AS (
        -- Document-level notes and per-vulnerability notes text.
        SELECT string_agg(n, ' ') AS txt
        FROM (
            SELECT jsonb_array_elements(doc #> '{document,notes}') ->> 'text' AS n
            UNION ALL
            SELECT jsonb_array_elements(
                       jsonb_path_query_array(doc, '$.vulnerabilities[*].notes[*]')) ->> 'text'
        ) AS all_notes(n)
        WHERE n IS NOT NULL
    )
    SELECT
        setweight(to_tsvector(cfg, (SELECT txt FROM title)),                 'A') ||
        setweight(to_tsvector(cfg, coalesce((SELECT txt FROM cves), '')),    'A') ||
        setweight(to_tsvector(cfg, coalesce((SELECT txt FROM products), '')),'B') ||
        setweight(to_tsvector(cfg, (SELECT txt FROM publisher)),             'B') ||
        setweight(to_tsvector(cfg, coalesce((SELECT txt FROM notes), '')),   'C');
$$ LANGUAGE SQL STABLE;

-- extract_tsv sets documents.tsv on the row being written. It runs BEFORE the
-- row hits disk (BEFORE INSERT/UPDATE) so it just assigns NEW.tsv. The language
-- is read straight from NEW.document rather than NEW.lang: generated columns are
-- not yet populated while a BEFORE trigger runs, so NEW.lang would be NULL here
-- and the vector would silently fall back to the unstemmed "simple" config.
CREATE OR REPLACE FUNCTION extract_tsv() RETURNS TRIGGER AS $$
    BEGIN
        NEW.tsv := document_tsv(
            NEW.document,
            fts_config(NEW.document #>> '{document,lang}'));
        RETURN NEW;
    END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS extract_tsv_trigger_insert ON documents;
CREATE TRIGGER extract_tsv_trigger_insert BEFORE INSERT
    ON documents
    FOR EACH ROW
    EXECUTE FUNCTION extract_tsv();

DROP TRIGGER IF EXISTS extract_tsv_trigger_update ON documents;
CREATE TRIGGER extract_tsv_trigger_update BEFORE UPDATE
    ON documents
    FOR EACH ROW
    WHEN (NEW.document <> OLD.document)
    EXECUTE FUNCTION extract_tsv();

CREATE INDEX IF NOT EXISTS documents_tsv_idx ON documents USING gin (tsv);

-- ---------------------------------------------------------------------------
-- 4. Idempotent backfill for rows that predate the triggers. Re-running this
--    migration (or running it against the seeded demo DB) converges every
--    existing row to the same facets a fresh insert would produce.
-- ---------------------------------------------------------------------------

-- CVEs.
WITH cves_from_document AS (
    SELECT
        id AS doc_id,
        jsonb_array_elements_text(
            jsonb_path_query_array(document, '$.vulnerabilities."cve"')) AS cve
    FROM documents
),
distinct_cves AS (
    SELECT DISTINCT cve FROM cves_from_document
)
INSERT INTO unique_cves (cve)
SELECT cve FROM distinct_cves
ON CONFLICT DO NOTHING;

-- documents_cves: both join columns are NOT NULL, so UNIQUE(documents_id, cve_id)
-- has no NULL-distinctness gap and ON CONFLICT DO NOTHING is genuinely idempotent
-- here (unlike documents_products below).
INSERT INTO documents_cves (documents_id, cve_id)
SELECT DISTINCT d.id, u.id
FROM documents d
CROSS JOIN LATERAL jsonb_array_elements_text(
    jsonb_path_query_array(d.document, '$.vulnerabilities."cve"')) AS j(cve)
JOIN unique_cves u ON u.cve = j.cve
ON CONFLICT DO NOTHING;

-- Products / vendors. Delete-then-insert, mirroring the extract_products()
-- trigger, rather than relying on ON CONFLICT DO NOTHING: vendor and product are
-- nullable and SQL treats NULL as distinct from NULL for UNIQUE constraints, so
-- the NULL-bearing rows (bare vendors (v, NULL), orphan/full-product names
-- (NULL, p)) never conflict and would be re-inserted on every re-run. Wiping the
-- target rows first makes the backfill converge to exactly the trigger's output
-- regardless of how many times it runs.
DELETE FROM documents_products;
INSERT INTO documents_products (documents_id, vendor, product)
SELECT DISTINCT d.id, p.vendor, p.product
FROM documents d
CROSS JOIN LATERAL document_product_pairs(d.document) AS p;

-- Full-text vectors. Recomputed unconditionally so a re-run reflects any change
-- to the weighting/config rules.
UPDATE documents
SET tsv = document_tsv(document, fts_config(lang));
